version: '3.8'

services:
  runner:
    image: runner:latest # You can use this image or build your own
    restart: always
    environment:
      - REPO_URL=https://github.com/Nejwid/TramSim-threads
      - RUNNER_TOKEN=A6LUGTJDX7N2IRVP7WWN36LJR562W
      - NAME=self-hosted-Latitude7410